# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'commonTech' do
pod 'JSQMessagesViewController'
pod 'Alamofire', '~> 3.0'
pod "OAuthSwift", "~> 0.4.8"
pod "PubNub"
pod 'EZAudio', '~> 1.1.2'
pod 'GPUImage'
pod "NMPopUpViewSwift"
pod 'SDWebImage', '~>3.7'

end

target 'commonTechTests' do
pod 'JSQMessagesViewController'
pod 'Alamofire', '~> 3.0'
pod "OAuthSwift", "~> 0.4.8"
pod "PubNub"
pod 'EZAudio', '~> 1.1.2'
pod 'GPUImage'
pod "NMPopUpViewSwift"
pod 'SDWebImage', '~>3.7'

end

target 'commonTechUITests' do
pod 'JSQMessagesViewController'
pod 'Alamofire', '~> 3.0'
pod "OAuthSwift", "~> 0.4.8"
pod "PubNub"
pod 'EZAudio', '~> 1.1.2'
pod 'GPUImage'
pod "NMPopUpViewSwift"
pod 'SDWebImage', '~>3.7'

end

